[USERS] Endpoint users register OT245 - 24
alkemyTech/OT245-Server pull request #14
Opened 2022-07-18 19:36 UTC by marattagian

[OT245 - 24](https://alkemy-labs.atlassian.net/browse/OT245-24)
### Description
**AS** user  
I **WANT TO** register in the system  
**SO** I can be part of it

Acceptance criteria:
-   Request to POST /auth/register
-   The endpoint should validate Name, Last Name, Email and Password fields.
-   Password must be encrypted.
-   Should return the generated user.

1.  Validate
2.  Encrypt password
3.  Store in database

Validation dependency  [express validator](https://express-validator.github.io/docs/)
Encryption dependency [bcrypt](https://github.com/kelektiv/node.bcrypt.js#readme)

### Evidence

![Screenshot from 2022-07-18 16-15-00](https://user-images.githubusercontent.com/68022732/179601115-feb30bcd-663f-48df-99ac-84eeee53462d.png)

![Screenshot from 2022-07-18 16-15-53](https://user-images.githubusercontent.com/68022732/179601090-1d82345d-244e-45c8-988a-5dc55aa35321.png)

![Screenshot from 2022-07-18 16-16-39](https://user-images.githubusercontent.com/68022732/179601052-752421c9-4e8b-44c3-ab89-ac3dfac090db.png)
#### Errors evidence
![image](https://user-images.githubusercontent.com/68022732/179777024-4f93f998-8a9b-4922-9cab-47a6b9deaeab.png)

2022-07-18 20:09 UTC, gabodmc commented
Estaria faltando evidencia de cuando le llega mal alguno de los campos

2022-07-19 01:45 UTC, miguelpuente commented on schemas/user.js
> +exports.user = {
quizás debería llamarse register ya que mi schema se llama login...

2022-07-19 01:47 UTC, miguelpuente commented on services/users.js
> +    const existantUser = await User.findOne({ where: { email: body.email } })
quizás debería ser un servicio de usuario la búsqueda por email

2022-07-19 01:53 UTC, R-Berrocal commented on services/users.js
> +    const existantUser = await User.findOne({ where: { email: body.email } })
si no estoy mal eso podria ser un middleware que valide o un custom,  pero creo que eso es una card, entonces lo que yo opino es que hagamos justo lo que nos pida la card

2022-07-19 02:03 UTC, marattagian commented on services/users.js
> +    const existantUser = await User.findOne({ where: { email: body.email } })
Eso mismo, no me quiero ir del scope de la tarea. Y eventualmente optimizarlo para poder reutilizar ese código.

2022-07-19 13:00 UTC, gabodmc requested changes
Va bien encaminado, solo unas correciones

2022-07-19 13:00 UTC, gabodmc commented on schemas/user.js
> +}
el schema seria users en plural para seguir el workflow del proyecto. Exportar esta validacion. Podria llamarse create/register

2022-07-19 13:00 UTC, gabodmc commented on services/users.js
> +    const existantUser = await User.findOne({ where: { email: body.email } })
Asi como lo mencionan, generaria una funcion dentro de este servicio que se llame "getUserByEmail" por ejemplo. 
Termina siendo algo que queda disponible para cualquier servicio que necesite buscar un usuario por mail en la db.

2022-07-19 13:00 UTC, gabodmc commented on services/users.js
> +exports.registUser = async (body) => {
createUser seria una mejor opcion para exportar esta funcion del servicio. Porque despues van a tener createOrganization, createNews, etc.

2022-07-19 14:55 UTC, gabodmc approved these changes
Bien las correcciones. Aprobado!

2022-07-19 14:56 UTC, itsnicolearias approved these changes

2022-07-19 16:21 UTC, R-Berrocal approved these changes
Buen pr!

2022-07-19 16:33 UTC, merged