[ORGANIZATION] endpoint GET public data of organization OT245-23
alkemyTech/OT245-Server pull request #18
Opened 2022-07-19 12:01 UTC by MauriDiPietro

[OT245-23](https://alkemy-labs.atlassian.net/browse/OT245-23)

**_Description_**

COMO usuario
QUIERO ver los datos de una Organización
PARA tener conocimiento sobre ella.

Criterios de aceptación: 

    Se debe realizar una petición GET hacia ruta /organization/public

    El endpoint debe devolver solamente los campos name, image, phone y address de la Organización

**_Evidence:_**

**Case database with data**

![imagen](https://user-images.githubusercontent.com/74677356/179744191-fe702996-43be-4595-8506-8037e38e3e77.png)

![imagen](https://user-images.githubusercontent.com/74677356/179644685-1771bb7b-d398-47bf-afc0-751f69eb3943.png)

**Case database empty**

![imagen](https://user-images.githubusercontent.com/74677356/179744773-9ddf343b-71fe-40eb-8f75-cc3ade531403.png)

![imagen](https://user-images.githubusercontent.com/74677356/179744834-739ba879-09d4-42f3-a9f1-016fd9c64cb9.png)

2022-07-19 13:10 UTC, gabodmc requested changes
Esta muy bien, solo unas pequeñas correcciones

2022-07-19 13:10 UTC, gabodmc commented on routes/index.js
> +router.use('/organization', organizationRouter)
Ya hay algunos prs donde llaman a los routers como el nombre del servicio/controlador (en este caso, organizations.js).
Charlenlo entre ustede y suban los routers con los nombres normalizados.

2022-07-19 13:10 UTC, gabodmc commented on services/organizations.js
> +exports.getOrganization = async () => {
Al ser un findall, seria getOrganizations

2022-07-19 13:10 UTC, gabodmc commented on database/seeders/20220719114048-create-organization.js
> +};
El seeder esta fuera del scope

2022-07-19 14:51 UTC, marattagian commented
Además, colocar la descripción de la card y los criterios de aceptación en inglés para mantener el idioma en todo el PR

2022-07-19 16:27 UTC, gabodmc approved these changes
Buenas correcciones. Aprobadisimo!

2022-07-19 17:55 UTC, R-Berrocal approved these changes
todo ok

2022-07-19 19:44 UTC, marattagian approved these changes
Muy buen PR

2022-07-20 00:06 UTC, itsnicolearias approved these changes

2022-07-20 12:26 UTC, merged