[Categories] Endpoint Detail Category OT245 - 42
alkemyTech/OT245-Server pull request #20
Opened 2022-07-19 16:18 UTC by R-Berrocal

https://alkemy-labs.atlassian.net/browse/OT245-42

**Description**
AS admin user
I WANT to obtain information on an individual category
to be able to manage it

**Criteria of acceptance:**
GET to /categories/:id . It will show all the fields of a category based on the id sent by parameter. In the event that it does not exist, it will return an error with a 404 status code

**Evidence**
![image](https://user-images.githubusercontent.com/88119333/179799613-d66a1a07-0c44-4d3e-992b-45c3c73184c5.png)
![image](https://user-images.githubusercontent.com/88119333/179799671-81229034-393a-47c6-9ffc-dade407135c1.png)
![image](https://user-images.githubusercontent.com/88119333/179799740-651b32f3-c3a7-4a45-941e-a20a6cdb1fd8.png)
![image](https://user-images.githubusercontent.com/88119333/179799832-508551a2-f0f0-4c4c-b3d5-ac9f1831f7dc.png)

2022-07-19 16:42 UTC, gabodmc requested changes
Lo veo bien. Solo unos cambios

2022-07-19 16:42 UTC, gabodmc commented on controllers/categories.js
> +  getId: catchAsync(async (req, res, next) => {
getById

2022-07-19 16:42 UTC, gabodmc commented on controllers/categories.js
> +      const category = await getCategoryId(req.params.id)
getCategoryById

2022-07-19 16:42 UTC, gabodmc commented on services/categories.js
> +exports.getCategoryId = async (id) => {
getCategoryById

2022-07-20 00:25 UTC, gabodmc approved these changes
Buenas correcciones. Adentrol el PR!

2022-07-20 00:28 UTC, itsnicolearias approved these changes

2022-07-20 05:55 UTC, miguelpuente approved these changes

2022-07-20 06:00 UTC, merged