[ Contact Form] Integrate sending emails OT245-28
alkemyTech/OT245-Server pull request #38
Opened 2022-07-22 22:09 UTC by CamiloLonM

[https://alkemy-labs.atlassian.net/browse/OT245-28](url)

![Captura de pantalla 2022-07-22 170642](https://user-images.githubusercontent.com/98825779/180574789-4dc5693a-0842-482d-a0e7-f2aad3869f58.png)

![visual code](https://user-images.githubusercontent.com/98825779/180574827-266ba1ee-8d0a-43f6-a934-e9d783916b4a.png)

2022-07-22 23:00 UTC, R-Berrocal approved these changes

2022-07-23 00:17 UTC, HinojosaAcevedoJ approved these changes

2022-07-23 15:01 UTC, gabodmc requested changes
Esta perfecto! Solo dos cambios en el package.json
Se te pasaron dos dependencias que no van

2022-07-23 15:01 UTC, gabodmc commented on package.json
> +    "i": "^0.3.7",
esto no va

2022-07-23 15:01 UTC, gabodmc commented on package.json
> +    "npm": "^8.15.0",
esta tampoco

2022-07-23 19:58 UTC, itsnicolearias approved these changes

2022-07-23 23:46 UTC, gabodmc approved these changes

2022-07-23 23:47 UTC, merged