[ENDPOINT] update news PUT /news/:id OT245 - 48
alkemyTech/OT245-Server pull request #42
Opened 2022-07-23 18:18 UTC by marattagian

[OT245 - 48](https://alkemy-labs.atlassian.net/browse/OT245-48)

**AS** admin user
I **WANT TO** update an existent new
**SO** I can keep information updated

**Acceptance Criteria:**
PUT `/news/:id` - Should validate the existence of the new with the given id in the parameters and then update the new and return it with the updated values. Otherwise should return an error.

### Evidence
#### Success Case
![Screenshot from 2022-07-23 15-05-17](https://user-images.githubusercontent.com/68022732/180617878-5a85a718-d805-4b51-bb11-c7aa4473d856.png)

![Screenshot from 2022-07-23 15-06-11](https://user-images.githubusercontent.com/68022732/180617827-cb0ab696-ef65-4df7-a72b-91af044972db.png)

![Screenshot from 2022-07-23 15-05-43](https://user-images.githubusercontent.com/68022732/180617844-16e5ca00-c5c4-4251-a4f8-c6f890d666c9.png)

![Screenshot from 2022-07-23 15-06-50](https://user-images.githubusercontent.com/68022732/180617829-92993e74-73a5-48fc-bbbe-e91ae2403435.png)

#### Error Case
![Screenshot from 2022-07-23 15-10-26](https://user-images.githubusercontent.com/68022732/180617804-108c7bc3-1ec1-4742-8dbf-a54e09291a88.png)

2022-07-23 23:43 UTC, gabodmc approved these changes
Bien resuelto!

2022-07-24 01:43 UTC, R-Berrocal approved these changes

2022-07-24 01:45 UTC, R-Berrocal requested changes

2022-07-24 01:45 UTC, R-Berrocal commented on services/news.js
> +    const user = await New.findByPk(id)
Acá es new y retornas new

2022-07-24 02:48 UTC, marattagian commented on services/news.js
> +    const user = await New.findByPk(id)
Una confusión en el naming

2022-07-24 04:11 UTC, R-Berrocal approved these changes

2022-07-24 04:12 UTC, R-Berrocal commented on services/news.js
> +    const user = await New.findByPk(id)
Suele pasar jajajja

2022-07-24 05:08 UTC, HinojosaAcevedoJ approved these changes

2022-07-24 12:31 UTC, merged