Ot245 21 create model, migration and base controller of activities
alkemyTech/OT245-Server pull request #5
Opened 2022-07-14 20:19 UTC by miguelpuente

[OT245-21](https://alkemy-labs.atlassian.net/browse/OT245-21)

> ![image](https://user-images.githubusercontent.com/96270076/179072022-142baa96-4186-4ee8-acef-327aaac40e9b.png)

**Evidence**

> ![image](https://user-images.githubusercontent.com/96270076/179075105-0fa14114-ff66-4b41-918a-ddd0ae0e3ef0.png)

2022-07-14 20:44 UTC, gabodmc requested changes
Muy buen pr. Un pequeño cambio en el controller:
activities.js

2022-07-14 21:49 UTC, miguelpuente reviewed
SEE CHANGES

2022-07-14 22:14 UTC, gabodmc requested changes
Bien, pero sigue el archivo de activitiescontroller.js en el pr

2022-07-14 22:55 UTC, miguelpuente commented
**Now yes**!!!

2022-07-14 23:06 UTC, marattagian approved these changes
Buen PR

2022-07-14 23:27 UTC, gabodmc approved these changes
Aprobado!!

2022-07-14 23:28 UTC, gabodmc requested changes
Me acabo de dar cuenta que le modelo esta en plural. Las entidades van en singular: Activity
Y por si las dudas un pequeño recordatorio: cuando se usa el comando sequelize model:generate , se debe llamar a la entidad con mayucusculas: sequelize model:generate --name Activity

2022-07-15 00:10 UTC, miguelpuente commented
Cambié a mano desde el celular...

> ![Screenshot_20220714-210625_Chrome](https://user-images.githubusercontent.com/96270076/179121235-da2f0f8c-d055-4d2c-b215-46d943f2851f.jpg)

2022-07-15 00:29 UTC, miguelpuente reviewed
Changes ok.

2022-07-15 10:39 UTC, MauriDiPietro approved these changes
todo ok!

2022-07-15 13:12 UTC, gabodmc requested changes
Es medio riesgoso cambiarlo desde el celu. Fijate que ahi te quedo mal el nombre de la migración.
En estos casos de sequelize, los conveniente borrar los archivos y volver a correr el comando de model:generate

2022-07-15 15:07 UTC, miguelpuente reviewed
Standardize names.

2022-07-15 15:44 UTC, gabodmc requested changes
Ojo con el run lint. Ese comando lo que hace es modificar todos los archivos del proyecto y puede generar conflictos innecesarios. Solo formatear codigo de los archivos en los que estamos trabajando.
El controller deberia ser activities.js (los controllers van en plural).
Archivos fuera del scope: 
helpers/validatejs
middlewares/validations.js
package-lock.json

2022-07-15 20:07 UTC, gabodmc requested changes
Las correcciones estan bien. Solo que ahora figura eliminado el package-lock.
Hay que sacarlo del pr, no eliminarlo de dev.

2022-07-15 20:09 UTC, miguelpuente reviewed
Changes ok.

2022-07-15 20:11 UTC, gabodmc commented
> Changes ok.

No, sigue el archivo como eliminado: 
![image](https://user-images.githubusercontent.com/79473217/179303578-97602b21-3132-4941-9e77-da425e1034d7.png)

2022-07-15 20:27 UTC, gabodmc approved these changes
Ahora si quedo de 10. Aprobado!

2022-07-15 20:37 UTC, miguelpuente commented
[ACTIVITY] create model, migration and base controller of activities OT245-21

2022-07-15 20:37 UTC, itsnicolearias approved these changes

2022-07-15 20:39 UTC, merged