Ot245-19
alkemyTech/OT245-Server pull request #6
Opened 2022-07-14 21:03 UTC by R-Berrocal

card: https://alkemy-labs.atlassian.net/browse/OT245-19

Descripción

Campos:
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
content: TEXT NOT NULL
image: VARCHAR NOT NULL
categoryId: Clave foranea hacia ID de Categories
timestamps y softDeletes

Evidence:
![image](https://user-images.githubusercontent.com/88119333/179084761-8a00463a-5bf6-485e-8e48-4246f268a807.png)

2022-07-14 21:50 UTC, gabodmc requested changes
Bien, solo unos cambios. Ademas de lo cometado cambiar el controller a news.js ya que los controladores son plulares

2022-07-14 21:50 UTC, gabodmc commented on database/migrations/20220714204413-create-new.js
> +        allowNull:false
Agregar references

2022-07-14 21:50 UTC, gabodmc commented on database/models/new.js
> +      // define association here
Relacionar con Category

2022-07-15 21:20 UTC, CamiloLonM approved these changes

2022-07-15 22:54 UTC, itsnicolearias approved these changes

2022-07-15 23:18 UTC, MauriDiPietro approved these changes

2022-07-16 00:46 UTC, gabodmc approved these changes

2022-07-16 04:09 UTC, merged