[SLIDES] endpoint update OT245-60
alkemyTech/OT245-Server pull request #62
Opened 2022-07-27 15:24 UTC by MauriDiPietro

[OT245-60](https://alkemy-labs.atlassian.net/browse/OT245-60)

**_Description_**

AS admin user
I WANT to be able to update Slides
TO have the updated information at the top of the page

**_Criteria of acceptance:_**

A PUT /Slides/:id request must be made

You must validate that the slide exists and update it, otherwise return an error.

**_Evidence:_**

**case update ok:**
![table-1](https://user-images.githubusercontent.com/74677356/181285763-a570f819-a7d5-4997-a704-51292f56f726.PNG)
![GET-2](https://user-images.githubusercontent.com/74677356/181285818-1f8a55b3-ca81-4766-8352-38b61b719cbb.PNG)
![PUT](https://user-images.githubusercontent.com/74677356/181285873-08c6b3b8-54ef-45ec-859b-fadbc26cec10.PNG)
![table-2](https://user-images.githubusercontent.com/74677356/181285894-680fb780-1fbb-4669-b2cf-a45929f1021e.PNG)

**case slide not exists in database:**
![image](https://user-images.githubusercontent.com/74677356/181285945-215af17c-2979-4e0e-a2bb-63b7dd441696.png)

2022-07-27 17:33 UTC, gabodmc approved these changes

2022-07-27 17:46 UTC, DamiBastos approved these changes

2022-07-27 20:00 UTC, itsnicolearias approved these changes

2022-07-27 20:15 UTC, R-Berrocal requested changes

2022-07-27 20:15 UTC, R-Berrocal commented on services/slides.js
> +    const slide = await Slide.findByPk(id)
Primero deberías buscar el slide con el id que te están mandando en el req.params y validas que exista  y luego actualizas, si actualizas primero y el slide no existe te mandará al catch

2022-07-27 22:21 UTC, marattagian commented on services/slides.js
> +    const slide = await Slide.findByPk(id)
Me sumo a lo que te comenta Rober

2022-07-28 00:55 UTC, MauriDiPietro commented on services/slides.js
> +    const slide = await Slide.findByPk(id)
Están en lo cierto, se me pasó.

2022-07-28 01:14 UTC, R-Berrocal approved these changes
Buenos cambios 👌

2022-07-28 17:41 UTC, merged