[Seed Users] OT245-77 - Create user seed
alkemyTech/OT245-Server pull request #73
Opened 2022-07-30 21:58 UTC by CamiloLonM

[https://alkemy-labs.atlassian.net/browse/OT245-77](url)

**Description**

AS admin user
I WANT to view test data
TO be able to test functionalities on the web.

**Criteria of acceptance:**
Create a seeder to populate the database with Users for testing. 10 standard and 10 regular users. Later, add their data in the README.md to allow other Members to use them.

![image](https://user-images.githubusercontent.com/98825779/181997114-db4304e2-cd25-4512-b252-2d459c0fef7f.png)

![image](https://user-images.githubusercontent.com/98825779/181999218-1b804d2a-4ad9-43e9-9783-9a61b190d7e2.png)

2022-07-31 15:01 UTC, gabodmc approved these changes

2022-07-31 23:42 UTC, miguelpuente approved these changes

2022-08-01 13:42 UTC, itsnicolearias requested changes

2022-08-01 13:42 UTC, itsnicolearias commented on database/seeders/20220729222239-roles.js
> +    description: 'Administator',
Esta genial, solo 2 correcciones "Administrator"

2022-08-01 13:42 UTC, itsnicolearias commented on database/seeders/20220729222239-roles.js
> +    name: 'Standart',
y "Standard"

2022-08-01 14:46 UTC, gabodmc requested changes
Se me pasaron esas correcciones. Me sumo a lo comentado por Niki

2022-08-01 15:39 UTC, CamiloLonM commented on database/seeders/20220729222239-roles.js
> +    name: 'Standart',
lista, corrección de nombres

2022-08-01 15:40 UTC, CamiloLonM commented
lista, corrección de nombres

2022-08-01 16:52 UTC, itsnicolearias approved these changes

2022-08-01 19:16 UTC, miguelpuente approved these changes
Buen ojo Niki!

2022-08-01 21:10 UTC, DamiBastos approved these changes

2022-08-02 00:52 UTC, HinojosaAcevedoJ approved these changes

2022-08-03 01:13 UTC, gabodmc approved these changes

2022-08-03 19:50 UTC, merged