[TESTIMONIALS]  model, migration and controller created for testimonials OT245-20
alkemyTech/OT245-Server pull request #8
Opened 2022-07-14 22:23 UTC by itsnicolearias

**Card:** https://alkemy-labs.atlassian.net/browse/OT245-20?atlOrigin=eyJpIjoiNzUxNjE2MzgxODc2NGQwZDhhYzZmODJmNjU3NWExZWMiLCJwIjoiaiJ9

**Fields:**
id: INTEGER NOT NULL AUTO_INCREMENT
name: VARCHAR NOT NULL
image: VARCHAR NULLABLE
content: VARCHAR NULLABLE
timestamps y softDeletes

**Evidence:**
![image](https://user-images.githubusercontent.com/96268221/179098214-0a978378-9c63-4bd1-8d0a-3b82e8d6fdc0.png)

2022-07-14 22:31 UTC, gabodmc requested changes
Buen pr. Solo un pequeño comentario.
Ademas, recordar que las entidades son singulares:
Testimonial
Y por si las dudas un pequeño recordatorio: cuando se usa el comando sequelize model:generate , se debe llamar a la entidad con mayucusculas: sequelize model:generate --name Testimonial

2022-07-14 22:31 UTC, gabodmc commented on database/migrations/20220714142601-create-testimonials.js
> +      updatedAt: {
Faltaria el deletedAt para el soft delete

2022-07-15 12:44 UTC, itsnicolearias commented on database/migrations/20220714142601-create-testimonials.js
> +      updatedAt: {
Ahi agrege los cambios!

2022-07-15 13:17 UTC, gabodmc approved these changes
Buenas correcciones. Aprobado!

2022-07-15 13:50 UTC, R-Berrocal approved these changes
Todo ok

2022-07-15 15:05 UTC, marattagian approved these changes
Todo en orden, buen PR

2022-07-15 17:23 UTC, DamiBastos approved these changes

2022-07-15 20:06 UTC, merged