[FIX] Organization update
alkemyTech/OT245-Server pull request #80
Opened 2022-08-03 21:28 UTC by HinojosaAcevedoJ

2022-08-03 21:39 UTC, DamiBastos approved these changes

2022-08-03 22:30 UTC, itsnicolearias approved these changes

2022-08-04 06:58 UTC, R-Berrocal requested changes

2022-08-04 06:58 UTC, R-Berrocal commented on services/organizations.js
> +      linkedin,
es mucha información, se puede cambiar por const {body} = req

2022-08-04 06:58 UTC, R-Berrocal commented on services/organizations.js
>      await Organization.update({
await Organization.update({...body})

2022-08-04 15:10 UTC, R-Berrocal approved these changes

2022-08-04 15:10 UTC, R-Berrocal commented on services/organizations.js
> +    await Organization.update({ body }, { where: { id } })
Colóca {...body}, de esta manera estarás opteniendo los atributos que vengan dentro del objeto body, si dejas body es como si estuvieras metiendo un objeto dentro de otro objeto y te mandará error, si quieres usar solo body, hazlo sin las llaves, ya que body es un objeto update(body, {where: {id} })

2022-08-04 15:29 UTC, merged