[OT245-78] add middlewares to protect admin routes
alkemyTech/OT245-Server pull request #86
Opened 2022-08-04 15:28 UTC by HinojosaAcevedoJ

[OT245-78](https://alkemy-labs.atlassian.net/browse/OT245-78?atlOrigin=eyJpIjoiNjM0NjBjOGFjYzhlNGFlYTkwYzcyMDBkMGU2NWY2OTAiLCJwIjoiaiJ9)

AS admin user
I WANT to control access to certain content
TO keep data protected

Criteria of acceptance:
The middlewares get added to avoid the operations of creating, updating and deleting the entities of the system.

Evidence:

with roleId 2 (Standard user):
![evidenceAdmin1](https://user-images.githubusercontent.com/38705539/182886272-a708a0ac-b211-4af7-8e0b-bc2c9dee4a2e.png)
![evidenceAdmin2](https://user-images.githubusercontent.com/38705539/182886287-7bab08bd-85dd-46da-8c89-36bf68530126.png)

with roleId 1 (Admin):
![evidenceAdmin3](https://user-images.githubusercontent.com/38705539/182886331-2080d3b8-478d-4d95-bd8d-5069be153623.png)
![evidenceAdmin4](https://user-images.githubusercontent.com/38705539/182886351-de7935ad-a762-4905-bf49-9e7faf404f99.png)

2022-08-04 16:15 UTC, R-Berrocal requested changes
Agregar validateToken antes de verifyAdmin para validar que el token sea válido y pertenezca a un usuario [validateToken, verifyAdmin,]

2022-08-04 16:15 UTC, R-Berrocal commented on routes/activities.js
> +router.post('/', verifyAdmin, schemaValidator(activity), post)
Antes de llamar a verifyAdmin llama a validateToken para que obligues a la persona  a mandarte un token, y le mandé los errores y sepa el error [validateToken, verifyAdmin,]

2022-08-04 17:46 UTC, R-Berrocal approved these changes
excelente!

2022-08-04 20:00 UTC, itsnicolearias approved these changes

2022-08-05 10:27 UTC, MauriDiPietro approved these changes

2022-08-05 13:38 UTC, gabodmc commented on routes/activities.js
> +router.post('/', verifyAdmin, schemaValidator(activity), post)
No seria necesario. Le estarias agregando una consulta innecesaria a la ruta.

2022-08-05 13:39 UTC, gabodmc approved these changes

2022-08-05 16:48 UTC, merged