[Comments] OT245-81- Endpoint creation Comments
alkemyTech/OT245-Server pull request #87
Opened 2022-08-04 17:51 UTC by CamiloLonM

[https://alkemy-labs.atlassian.net/browse/OT245-81](url)

**Description**

AS user
I WANT to register new Comments
TO add them to an existing post

**Criteria of acceptance:**

POST /comments - You will need to validate that the news_id, user_id and body fields are sent.

**Empty body**
![Cuerpo vacio](https://user-images.githubusercontent.com/98825779/182916904-ae718f57-721f-4c48-ab23-a6a769aacd3b.png)

**wrong field**
![Datos campo erroneo](https://user-images.githubusercontent.com/98825779/182917019-56ea6b09-6f45-4f18-9240-866ef004cd46.png)

**Error New y User**
![new error](https://user-images.githubusercontent.com/98825779/182917318-9c209845-b260-41bf-b297-083aeecc6aea.png)
![user no found](https://user-images.githubusercontent.com/98825779/182917332-113e7016-8f5e-498e-993e-049d67a721e3.png)

**OK!!**
![post OK](https://user-images.githubusercontent.com/98825779/182917389-9d4202e2-564b-47cd-bae3-ae5b85462769.png)

2022-08-04 17:56 UTC, CamiloLonM commented
El eslint no permite pasar las userId por User_id , y newId por news_Id como lo pide la cart.
![eslint problema al destructuración](https://user-images.githubusercontent.com/98825779/182918227-e30c0f50-e118-4b76-8a5e-212d63759026.png)
.

2022-08-04 23:05 UTC, R-Berrocal requested changes

2022-08-04 23:05 UTC, R-Berrocal commented on schemas/comments.js
> +      errorMessage: 'user_id cannot be null',
userId cannot be null

2022-08-04 23:05 UTC, R-Berrocal commented on schemas/comments.js
> +      errorMessage: 'new_id cannot be null',
newId cannot be null

2022-08-05 13:34 UTC, gabodmc approved these changes
Solo corregir los typos que menciona Roberto

2022-08-05 15:58 UTC, marattagian approved these changes

2022-08-05 17:07 UTC, R-Berrocal approved these changes
Buena!

2022-08-05 17:51 UTC, merged