[COMMENTS] endpoint for delete comments OT245-83
alkemyTech/OT245-Server pull request #89
Opened 2022-08-04 23:31 UTC by itsnicolearias

**CARD:** https://alkemy-labs.atlassian.net/jira/software/c/projects/OT245/boards/335?modal=detail&selectedIssue=OT245-83

**ACCEPTANCE **CRITERIA:****

AS user
I WANT to delete a comment
TO moderate the content

`DELETE /comments/:id `- Ii should validate the existance of the comment. Only could delete the comment the creator or an admin user.

**EVIDENCE:**
[IF THE COMMENT DOESN'T EXISTS]
![image](https://user-images.githubusercontent.com/96268221/182971681-b6457df5-7f76-439e-8a26-f7ed89caf323.png)

[IF THERE'S NO TOKEN]
![image](https://user-images.githubusercontent.com/96268221/182971822-cc6cdeea-fbc6-4d8d-9c3b-23675a98f704.png)

[IF THE TOKEN IS INVALID]
![image](https://user-images.githubusercontent.com/96268221/182971753-86dc5abe-0732-4843-b5ac-1b9b127da8dd.png)

[UNAUTHORIZED USER]
![image](https://user-images.githubusercontent.com/96268221/182971971-c582e822-b828-48b2-90d1-51574229bda5.png)

[IF THE USER IS ADMIN OR IS THE CREATOR OF THE COMMENT]
![image](https://user-images.githubusercontent.com/96268221/182972110-03636151-24d1-465d-a2fe-5530d24fa700.png)

2022-08-05 13:36 UTC, gabodmc approved these changes

2022-08-05 15:48 UTC, DamiBastos approved these changes

2022-08-05 15:55 UTC, marattagian approved these changes

2022-08-05 17:56 UTC, CamiloLonM approved these changes

2022-08-05 18:58 UTC, R-Berrocal requested changes

2022-08-05 18:58 UTC, R-Berrocal commented on routes/comments.js
> +router.delete('/:id', validateToken, destroy)
acá se debería usar el [validateToken, verifyOwnerShip] para que no tengas problemas con el id del usuario y el de comments a eliminar puedes separarlo en dos parámetros router.delete('/:id ( este seria el del usuario ya que ownerShip verifica que en el param venga un req.param.id) /:commentId (aqui mandarias el id del comentario)')

en teoria te quedaria asi router.delete('/:id/:commentId',[],destroy)

2022-08-05 18:58 UTC, R-Berrocal commented on services/comments.js
> +    }
si usas verifyOwnerShip ya no tendrías que hacer esta validación acá

2022-08-05 20:26 UTC, itsnicolearias commented on routes/comments.js
> +router.delete('/:id', validateToken, destroy)
si no se me habia ocurrido, por eso le meti la validacion, ahora lo arreglo :+1:

2022-08-06 13:05 UTC, MauriDiPietro requested changes
Fijate que tiene conflictos con:

controllers/comments.js
routes/comments.js
services/comments.js

2022-08-08 23:54 UTC, R-Berrocal approved these changes

2022-08-09 15:11 UTC, MauriDiPietro approved these changes

2022-08-09 19:43 UTC, merged